//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Foundation.Campaign.Connected_Services.SessionService
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [DataContract(Name="WebserviceException", Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class WebserviceException : object
    {
        
        private object causeField;
        
        private string messageField;
        
        [DataMember(IsRequired=true)]
        public object cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session", ConfigurationName="SessionService.SessionWebservice")]
    public interface SessionWebservice
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.setMediaTypeResponse> setMediaTypeAsync(SessionService.setMediaTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.getMediaTypeResponse> getMediaTypeAsync(SessionService.getMediaTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.getLocaleResponse> getLocaleAsync(SessionService.getLocaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.setLocaleResponse> setLocaleAsync(SessionService.setLocaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.loginResponse> loginAsync(SessionService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.logoutResponse> logoutAsync(SessionService.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SessionService.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<SessionService.getVersionResponse> getVersionAsync(SessionService.getVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMediaTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMediaType", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.setMediaTypeRequestBody Body;
        
        public setMediaTypeRequest()
        {
        }
        
        public setMediaTypeRequest(SessionService.setMediaTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class setMediaTypeRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public setMediaTypeRequestBody()
        {
        }
        
        public setMediaTypeRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMediaTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMediaTypeResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.setMediaTypeResponseBody Body;
        
        public setMediaTypeResponse()
        {
        }
        
        public setMediaTypeResponse(SessionService.setMediaTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class setMediaTypeResponseBody
    {
        
        public setMediaTypeResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMediaType", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.getMediaTypeRequestBody Body;
        
        public getMediaTypeRequest()
        {
        }
        
        public getMediaTypeRequest(SessionService.getMediaTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getMediaTypeRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getMediaTypeRequestBody()
        {
        }
        
        public getMediaTypeRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMediaTypeResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.getMediaTypeResponseBody Body;
        
        public getMediaTypeResponse()
        {
        }
        
        public getMediaTypeResponse(SessionService.getMediaTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getMediaTypeResponseBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string getMediaTypeReturn;
        
        public getMediaTypeResponseBody()
        {
        }
        
        public getMediaTypeResponseBody(string getMediaTypeReturn)
        {
            this.getMediaTypeReturn = getMediaTypeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocale", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.getLocaleRequestBody Body;
        
        public getLocaleRequest()
        {
        }
        
        public getLocaleRequest(SessionService.getLocaleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getLocaleRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getLocaleRequestBody()
        {
        }
        
        public getLocaleRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocaleResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.getLocaleResponseBody Body;
        
        public getLocaleResponse()
        {
        }
        
        public getLocaleResponse(SessionService.getLocaleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getLocaleResponseBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string getLocaleReturn;
        
        public getLocaleResponseBody()
        {
        }
        
        public getLocaleResponseBody(string getLocaleReturn)
        {
            this.getLocaleReturn = getLocaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setLocaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setLocale", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.setLocaleRequestBody Body;
        
        public setLocaleRequest()
        {
        }
        
        public setLocaleRequest(SessionService.setLocaleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class setLocaleRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public setLocaleRequestBody()
        {
        }
        
        public setLocaleRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setLocaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setLocaleResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.setLocaleResponseBody Body;
        
        public setLocaleResponse()
        {
        }
        
        public setLocaleResponse(SessionService.setLocaleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class setLocaleResponseBody
    {
        
        public setLocaleResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.loginRequestBody Body;
        
        public loginRequest()
        {
        }
        
        public loginRequest(SessionService.loginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class loginRequestBody
    {
        
        [DataMember(Order=0)]
        public long in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string in2;
        
        public loginRequestBody()
        {
        }
        
        public loginRequestBody(long in0, string in1, string in2)
        {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.loginResponseBody Body;
        
        public loginResponse()
        {
        }
        
        public loginResponse(SessionService.loginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class loginResponseBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string loginReturn;
        
        public loginResponseBody()
        {
        }
        
        public loginResponseBody(string loginReturn)
        {
            this.loginReturn = loginReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.logoutRequestBody Body;
        
        public logoutRequest()
        {
        }
        
        public logoutRequest(SessionService.logoutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class logoutRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public logoutRequestBody()
        {
        }
        
        public logoutRequestBody(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.logoutResponseBody Body;
        
        public logoutResponse()
        {
        }
        
        public logoutResponse(SessionService.logoutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class logoutResponseBody
    {
        
        public logoutResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersion", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.getVersionRequestBody Body;
        
        public getVersionRequest()
        {
        }
        
        public getVersionRequest(SessionService.getVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class getVersionRequestBody
    {
        
        public getVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersionResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public SessionService.getVersionResponseBody Body;
        
        public getVersionResponse()
        {
        }
        
        public getVersionResponse(SessionService.getVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getVersionResponseBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string getVersionReturn;
        
        public getVersionResponseBody()
        {
        }
        
        public getVersionResponseBody(string getVersionReturn)
        {
            this.getVersionReturn = getVersionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SessionWebserviceChannel : SessionService.SessionWebservice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SessionWebserviceClient : System.ServiceModel.ClientBase<SessionService.SessionWebservice>, SessionService.SessionWebservice
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SessionWebserviceClient() : 
                base(SessionWebserviceClient.GetDefaultBinding(), SessionWebserviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Session.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebserviceClient(EndpointConfiguration endpointConfiguration) : 
                base(SessionWebserviceClient.GetBindingForEndpoint(endpointConfiguration), SessionWebserviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebserviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SessionWebserviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebserviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SessionWebserviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.setMediaTypeResponse> SessionService.SessionWebservice.setMediaTypeAsync(SessionService.setMediaTypeRequest request)
        {
            return base.Channel.setMediaTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.setMediaTypeResponse> setMediaTypeAsync(string in0, string in1)
        {
            SessionService.setMediaTypeRequest inValue = new SessionService.setMediaTypeRequest();
            inValue.Body = new SessionService.setMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((SessionService.SessionWebservice)(this)).setMediaTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.getMediaTypeResponse> SessionService.SessionWebservice.getMediaTypeAsync(SessionService.getMediaTypeRequest request)
        {
            return base.Channel.getMediaTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.getMediaTypeResponse> getMediaTypeAsync(string in0)
        {
            SessionService.getMediaTypeRequest inValue = new SessionService.getMediaTypeRequest();
            inValue.Body = new SessionService.getMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            return ((SessionService.SessionWebservice)(this)).getMediaTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.getLocaleResponse> SessionService.SessionWebservice.getLocaleAsync(SessionService.getLocaleRequest request)
        {
            return base.Channel.getLocaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.getLocaleResponse> getLocaleAsync(string in0)
        {
            SessionService.getLocaleRequest inValue = new SessionService.getLocaleRequest();
            inValue.Body = new SessionService.getLocaleRequestBody();
            inValue.Body.in0 = in0;
            return ((SessionService.SessionWebservice)(this)).getLocaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.setLocaleResponse> SessionService.SessionWebservice.setLocaleAsync(SessionService.setLocaleRequest request)
        {
            return base.Channel.setLocaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.setLocaleResponse> setLocaleAsync(string in0, string in1)
        {
            SessionService.setLocaleRequest inValue = new SessionService.setLocaleRequest();
            inValue.Body = new SessionService.setLocaleRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((SessionService.SessionWebservice)(this)).setLocaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.loginResponse> SessionService.SessionWebservice.loginAsync(SessionService.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.loginResponse> loginAsync(long in0, string in1, string in2)
        {
            SessionService.loginRequest inValue = new SessionService.loginRequest();
            inValue.Body = new SessionService.loginRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            inValue.Body.in2 = in2;
            return ((SessionService.SessionWebservice)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.logoutResponse> SessionService.SessionWebservice.logoutAsync(SessionService.logoutRequest request)
        {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.logoutResponse> logoutAsync(string in0)
        {
            SessionService.logoutRequest inValue = new SessionService.logoutRequest();
            inValue.Body = new SessionService.logoutRequestBody();
            inValue.Body.in0 = in0;
            return ((SessionService.SessionWebservice)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionService.getVersionResponse> SessionService.SessionWebservice.getVersionAsync(SessionService.getVersionRequest request)
        {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionService.getVersionResponse> getVersionAsync()
        {
            SessionService.getVersionRequest inValue = new SessionService.getVersionRequest();
            inValue.Body = new SessionService.getVersionRequestBody();
            return ((SessionService.SessionWebservice)(this)).getVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Session))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Session))
            {
                return new System.ServiceModel.EndpointAddress("https://api.campaign.episerver.net/soap11/Session");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SessionWebserviceClient.GetBindingForEndpoint(EndpointConfiguration.Session);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SessionWebserviceClient.GetEndpointAddress(EndpointConfiguration.Session);
        }
        
        public enum EndpointConfiguration
        {
            
            Session,
        }
    }
}
