using EPiServer.Framework.DataAnnotations;
using EPiServer.Social.ActivityStreams.Core;
using EPiServer.Social.Common;
using EPiServer.Web.Routing;
using Foundation.Social;
using Foundation.Social.Adapters;
using Foundation.Social.Models.ActivityStreams;
using Foundation.Social.Repositories.ActivityStreams;
using Foundation.Social.Repositories.Common;
using Foundation.Social.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Foundation.Features.Blocks.FeedBlock
{
    /// <summary>
    /// The FeedBlockController handles the rendering of feed items, if any, that were automatically
    /// generated by the Social Activity Streams system in response to activities occuring on any 
    /// target items that the logged in user has subscribed to.
    /// </summary>
    [TemplateDescriptor(Default = true)]
    public class FeedBlockController : SocialBlockController<FeedBlock>
    {
        private readonly IUserRepository _userRepository;
        private readonly ICommunityFeedRepository _feedRepository;
        private readonly ICommunityActivityAdapter _communityActivityAdapter;
        private const string ErrorMessage = "Error";
        private const string ErrorGettingUserIdMessage = "There was an error identifying the logged in user. Please make sure you are logged in and try again.";

        /// <summary>
        /// Constructor
        /// </summary>
        public FeedBlockController(IUserRepository userRepository, ICommunityFeedRepository communityFeedRepository, IPageRouteHelper pageRouteHelper
            , ICommunityActivityAdapter communityActivityAdapter) : base(pageRouteHelper)
        {
            _userRepository = userRepository;
            _feedRepository = communityFeedRepository;
            _communityActivityAdapter = communityActivityAdapter;
        }

        /// <summary>
        /// Render the feed block frontend view.
        /// </summary>
        /// <param name="currentBlock">The current frontend block instance.</param>
        /// <returns>The action's result.</returns>
        public override ActionResult Index(FeedBlock currentBlock)
        {
            // Create a feed block view model to fill the frontend block view
            var blockViewModel = new FeedBlockViewModel(currentBlock)
            {
                Messages = new List<MessageViewModel>()
            };

            // If user logged in, retrieve activity feed for logged in user
            if (User.Identity.IsAuthenticated)
            {
                GetSocialActivityFeed(currentBlock, blockViewModel);
            }

            return PartialView("~/Features/Blocks/FeedBlock/FeedBlock.cshtml", blockViewModel);
        }

        /// <summary>
        /// Gets the activity feed for the logged in user
        /// </summary>
        /// <param name="currentBlock">The current frontend block instance.</param>
        /// <param name="blockViewModel">a reference to the FeedBlockViewModel to 
        ///populate with activity feed for the logged in user and errors, if any</param>
        private void GetSocialActivityFeed(FeedBlock currentBlock, FeedBlockViewModel blockViewModel)
        {

            try
            {
                var userId = _userRepository.GetUserId(User);

                if (!string.IsNullOrWhiteSpace(userId))
                {
                    blockViewModel.Feed = _feedRepository.Get(new CommunityFeedFilter
                    {
                        Subscriber = userId,
                        PageSize = currentBlock.FeedDisplayMax
                    });
                }
                else
                {
                    blockViewModel.Messages.Add(new MessageViewModel(ErrorGettingUserIdMessage, ErrorMessage));
                }
            }
            catch (SocialRepositoryException ex)
            {
                blockViewModel.Messages.Add(new MessageViewModel(ex.Message, ErrorMessage));
            }
        }

        private IEnumerable<CommunityFeedItemViewModel> AdaptFeedItems(
            List<Composite<FeedItem, CommunityActivity>> feedItems) => feedItems.Select(c => _communityActivityAdapter.Adapt(c));
    }
}