//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Campaign.Connected_Services.RecipientList
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList")]
    public partial class WebserviceException
    {
        
        private object causeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", ConfigurationName="RecipientList.RecipientListWebservice")]
    public interface RecipientListWebservice
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isTestRecipientListReturn")]
        System.Threading.Tasks.Task<bool> isTestRecipientListAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setTestRecipientListAsync(string in0, long in1, bool in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipientList.getAllIdsResponse> getAllIdsAsync(RecipientList.getAllIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipientList.getDataSetResponse> getDataSetAsync(RecipientList.getDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipientList.getColumnNamesResponse> getColumnNamesAsync(RecipientList.getColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipientList.getDataSetFlatResponse> getDataSetFlatAsync(RecipientList.getDataSetFlatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCountReturn")]
        System.Threading.Tasks.Task<int> getCountAsync(string in0, bool in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getNameReturn")]
        System.Threading.Tasks.Task<string> getNameAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setNameAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="copyReturn")]
        System.Threading.Tasks.Task<long> copyAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setDescriptionAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDescriptionReturn")]
        System.Threading.Tasks.Task<string> getDescriptionAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecipientList.getAttributeNamesResponse> getAttributeNamesAsync(RecipientList.getAttributeNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecipientList.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        System.Threading.Tasks.Task<string> getVersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllIds", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAllIdsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getAllIdsRequest()
        {
        }
        
        public getAllIdsRequest(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllIdsResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAllIdsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAllIdsReturn")]
        public long[] getAllIdsReturn;
        
        public getAllIdsResponse()
        {
        }
        
        public getAllIdsResponse(long[] getAllIdsReturn)
        {
            this.getAllIdsReturn = getAllIdsReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList")]
    public partial class ArrayOf_xsd_string
    {
        
        private string[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Order=0)]
        public string[] item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSet", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getDataSetRequest()
        {
        }
        
        public getDataSetRequest(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getDataSetReturn")]
        public RecipientList.ArrayOf_xsd_string[] getDataSetReturn;
        
        public getDataSetResponse()
        {
        }
        
        public getDataSetResponse(RecipientList.ArrayOf_xsd_string[] getDataSetReturn)
        {
            this.getDataSetReturn = getDataSetReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnNames", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getColumnNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getColumnNamesRequest()
        {
        }
        
        public getColumnNamesRequest(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnNamesResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getColumnNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getColumnNamesReturn")]
        public string[] getColumnNamesReturn;
        
        public getColumnNamesResponse()
        {
        }
        
        public getColumnNamesResponse(string[] getColumnNamesReturn)
        {
            this.getColumnNamesReturn = getColumnNamesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetFlat", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetFlatRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getDataSetFlatRequest()
        {
        }
        
        public getDataSetFlatRequest(string in0)
        {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetFlatResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetFlatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getDataSetFlatReturn")]
        public string[] getDataSetFlatReturn;
        
        public getDataSetFlatResponse()
        {
        }
        
        public getDataSetFlatResponse(string[] getDataSetFlatReturn)
        {
            this.getDataSetFlatReturn = getDataSetFlatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttributeNames", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAttributeNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=2)]
        public string in2;
        
        public getAttributeNamesRequest()
        {
        }
        
        public getAttributeNamesRequest(string in0, long in1, string in2)
        {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttributeNamesResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAttributeNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAttributeNamesReturn")]
        public string[] getAttributeNamesReturn;
        
        public getAttributeNamesResponse()
        {
        }
        
        public getAttributeNamesResponse(string[] getAttributeNamesReturn)
        {
            this.getAttributeNamesReturn = getAttributeNamesReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface RecipientListWebserviceChannel : RecipientList.RecipientListWebservice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class RecipientListWebserviceClient : System.ServiceModel.ClientBase<RecipientList.RecipientListWebservice>, RecipientList.RecipientListWebservice
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecipientListWebserviceClient() : 
                base(RecipientListWebserviceClient.GetDefaultBinding(), RecipientListWebserviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RecipientList.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipientListWebserviceClient(EndpointConfiguration endpointConfiguration) : 
                base(RecipientListWebserviceClient.GetBindingForEndpoint(endpointConfiguration), RecipientListWebserviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipientListWebserviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecipientListWebserviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipientListWebserviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecipientListWebserviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecipientListWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> isTestRecipientListAsync(string in0, long in1)
        {
            return base.Channel.isTestRecipientListAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task setTestRecipientListAsync(string in0, long in1, bool in2)
        {
            return base.Channel.setTestRecipientListAsync(in0, in1, in2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipientList.getAllIdsResponse> RecipientList.RecipientListWebservice.getAllIdsAsync(RecipientList.getAllIdsRequest request)
        {
            return base.Channel.getAllIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipientList.getAllIdsResponse> getAllIdsAsync(string in0)
        {
            RecipientList.getAllIdsRequest inValue = new RecipientList.getAllIdsRequest();
            inValue.in0 = in0;
            return ((RecipientList.RecipientListWebservice)(this)).getAllIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipientList.getDataSetResponse> RecipientList.RecipientListWebservice.getDataSetAsync(RecipientList.getDataSetRequest request)
        {
            return base.Channel.getDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipientList.getDataSetResponse> getDataSetAsync(string in0)
        {
            RecipientList.getDataSetRequest inValue = new RecipientList.getDataSetRequest();
            inValue.in0 = in0;
            return ((RecipientList.RecipientListWebservice)(this)).getDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipientList.getColumnNamesResponse> RecipientList.RecipientListWebservice.getColumnNamesAsync(RecipientList.getColumnNamesRequest request)
        {
            return base.Channel.getColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipientList.getColumnNamesResponse> getColumnNamesAsync(string in0)
        {
            RecipientList.getColumnNamesRequest inValue = new RecipientList.getColumnNamesRequest();
            inValue.in0 = in0;
            return ((RecipientList.RecipientListWebservice)(this)).getColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipientList.getDataSetFlatResponse> RecipientList.RecipientListWebservice.getDataSetFlatAsync(RecipientList.getDataSetFlatRequest request)
        {
            return base.Channel.getDataSetFlatAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipientList.getDataSetFlatResponse> getDataSetFlatAsync(string in0)
        {
            RecipientList.getDataSetFlatRequest inValue = new RecipientList.getDataSetFlatRequest();
            inValue.in0 = in0;
            return ((RecipientList.RecipientListWebservice)(this)).getDataSetFlatAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> getCountAsync(string in0, bool in1)
        {
            return base.Channel.getCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getNameAsync(string in0, long in1)
        {
            return base.Channel.getNameAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task setNameAsync(string in0, long in1, string in2)
        {
            return base.Channel.setNameAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<long> copyAsync(string in0, long in1)
        {
            return base.Channel.copyAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task setDescriptionAsync(string in0, long in1, string in2)
        {
            return base.Channel.setDescriptionAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getDescriptionAsync(string in0, long in1)
        {
            return base.Channel.getDescriptionAsync(in0, in1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecipientList.getAttributeNamesResponse> RecipientList.RecipientListWebservice.getAttributeNamesAsync(RecipientList.getAttributeNamesRequest request)
        {
            return base.Channel.getAttributeNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecipientList.getAttributeNamesResponse> getAttributeNamesAsync(string in0, long in1, string in2)
        {
            RecipientList.getAttributeNamesRequest inValue = new RecipientList.getAttributeNamesRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((RecipientList.RecipientListWebservice)(this)).getAttributeNamesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> getVersionAsync()
        {
            return base.Channel.getVersionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecipientList))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecipientList))
            {
                return new System.ServiceModel.EndpointAddress("https://api.campaign.episerver.net/soap11/RecipientList");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecipientListWebserviceClient.GetBindingForEndpoint(EndpointConfiguration.RecipientList);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecipientListWebserviceClient.GetEndpointAddress(EndpointConfiguration.RecipientList);
        }
        
        public enum EndpointConfiguration
        {
            
            RecipientList,
        }
    }
}
