//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Foundation.Campaign.Connected_Services.MailId
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [DataContract(Name="WebserviceException", Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class WebserviceException : object
    {
        
        private object causeField;
        
        private string messageField;
        
        [DataMember(IsRequired=true)]
        public object cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId", ConfigurationName="MailId.MailIdWebservice")]
    public interface MailIdWebservice
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MailId.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<MailId.getMailingIdResponse> getMailingIdAsync(MailId.getMailingIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MailId.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<MailId.getRecipientListIdResponse> getRecipientListIdAsync(MailId.getRecipientListIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MailId.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<MailId.getRecipientIdResponse> getRecipientIdAsync(MailId.getRecipientIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MailId.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<MailId.getMandatorIdResponse> getMandatorIdAsync(MailId.getMandatorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MailId.WebserviceException), Action="", Name="fault")]
        System.Threading.Tasks.Task<MailId.getVersionResponse> getVersionAsync(MailId.getVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMailingIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMailingId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getMailingIdRequestBody Body;
        
        public getMailingIdRequest()
        {
        }
        
        public getMailingIdRequest(MailId.getMailingIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMailingIdRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getMailingIdRequestBody()
        {
        }
        
        public getMailingIdRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMailingIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMailingIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getMailingIdResponseBody Body;
        
        public getMailingIdResponse()
        {
        }
        
        public getMailingIdResponse(MailId.getMailingIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMailingIdResponseBody
    {
        
        [DataMember(Order=0)]
        public long getMailingIdReturn;
        
        public getMailingIdResponseBody()
        {
        }
        
        public getMailingIdResponseBody(long getMailingIdReturn)
        {
            this.getMailingIdReturn = getMailingIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientListIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientListId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getRecipientListIdRequestBody Body;
        
        public getRecipientListIdRequest()
        {
        }
        
        public getRecipientListIdRequest(MailId.getRecipientListIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientListIdRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getRecipientListIdRequestBody()
        {
        }
        
        public getRecipientListIdRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientListIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientListIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getRecipientListIdResponseBody Body;
        
        public getRecipientListIdResponse()
        {
        }
        
        public getRecipientListIdResponse(MailId.getRecipientListIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientListIdResponseBody
    {
        
        [DataMember(Order=0)]
        public long getRecipientListIdReturn;
        
        public getRecipientListIdResponseBody()
        {
        }
        
        public getRecipientListIdResponseBody(long getRecipientListIdReturn)
        {
            this.getRecipientListIdReturn = getRecipientListIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getRecipientIdRequestBody Body;
        
        public getRecipientIdRequest()
        {
        }
        
        public getRecipientIdRequest(MailId.getRecipientIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientIdRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getRecipientIdRequestBody()
        {
        }
        
        public getRecipientIdRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getRecipientIdResponseBody Body;
        
        public getRecipientIdResponse()
        {
        }
        
        public getRecipientIdResponse(MailId.getRecipientIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientIdResponseBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string getRecipientIdReturn;
        
        public getRecipientIdResponseBody()
        {
        }
        
        public getRecipientIdResponseBody(string getRecipientIdReturn)
        {
            this.getRecipientIdReturn = getRecipientIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMandatorIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMandatorId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getMandatorIdRequestBody Body;
        
        public getMandatorIdRequest()
        {
        }
        
        public getMandatorIdRequest(MailId.getMandatorIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMandatorIdRequestBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getMandatorIdRequestBody()
        {
        }
        
        public getMandatorIdRequestBody(string in0, string in1)
        {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMandatorIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMandatorIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getMandatorIdResponseBody Body;
        
        public getMandatorIdResponse()
        {
        }
        
        public getMandatorIdResponse(MailId.getMandatorIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMandatorIdResponseBody
    {
        
        [DataMember(Order=0)]
        public long getMandatorIdReturn;
        
        public getMandatorIdResponseBody()
        {
        }
        
        public getMandatorIdResponseBody(long getMandatorIdReturn)
        {
            this.getMandatorIdReturn = getMandatorIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersion", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getVersionRequestBody Body;
        
        public getVersionRequest()
        {
        }
        
        public getVersionRequest(MailId.getVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class getVersionRequestBody
    {
        
        public getVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersionResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public MailId.getVersionResponseBody Body;
        
        public getVersionResponse()
        {
        }
        
        public getVersionResponse(MailId.getVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getVersionResponseBody
    {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string getVersionReturn;
        
        public getVersionResponseBody()
        {
        }
        
        public getVersionResponseBody(string getVersionReturn)
        {
            this.getVersionReturn = getVersionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface MailIdWebserviceChannel : MailId.MailIdWebservice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class MailIdWebserviceClient : System.ServiceModel.ClientBase<MailId.MailIdWebservice>, MailId.MailIdWebservice
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailIdWebserviceClient() : 
                base(MailIdWebserviceClient.GetDefaultBinding(), MailIdWebserviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MailId.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailIdWebserviceClient(EndpointConfiguration endpointConfiguration) : 
                base(MailIdWebserviceClient.GetBindingForEndpoint(endpointConfiguration), MailIdWebserviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailIdWebserviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailIdWebserviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailIdWebserviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailIdWebserviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailIdWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailId.getMailingIdResponse> MailId.MailIdWebservice.getMailingIdAsync(MailId.getMailingIdRequest request)
        {
            return base.Channel.getMailingIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailId.getMailingIdResponse> getMailingIdAsync(string in0, string in1)
        {
            MailId.getMailingIdRequest inValue = new MailId.getMailingIdRequest();
            inValue.Body = new MailId.getMailingIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((MailId.MailIdWebservice)(this)).getMailingIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailId.getRecipientListIdResponse> MailId.MailIdWebservice.getRecipientListIdAsync(MailId.getRecipientListIdRequest request)
        {
            return base.Channel.getRecipientListIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailId.getRecipientListIdResponse> getRecipientListIdAsync(string in0, string in1)
        {
            MailId.getRecipientListIdRequest inValue = new MailId.getRecipientListIdRequest();
            inValue.Body = new MailId.getRecipientListIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((MailId.MailIdWebservice)(this)).getRecipientListIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailId.getRecipientIdResponse> MailId.MailIdWebservice.getRecipientIdAsync(MailId.getRecipientIdRequest request)
        {
            return base.Channel.getRecipientIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailId.getRecipientIdResponse> getRecipientIdAsync(string in0, string in1)
        {
            MailId.getRecipientIdRequest inValue = new MailId.getRecipientIdRequest();
            inValue.Body = new MailId.getRecipientIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((MailId.MailIdWebservice)(this)).getRecipientIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailId.getMandatorIdResponse> MailId.MailIdWebservice.getMandatorIdAsync(MailId.getMandatorIdRequest request)
        {
            return base.Channel.getMandatorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailId.getMandatorIdResponse> getMandatorIdAsync(string in0, string in1)
        {
            MailId.getMandatorIdRequest inValue = new MailId.getMandatorIdRequest();
            inValue.Body = new MailId.getMandatorIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((MailId.MailIdWebservice)(this)).getMandatorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailId.getVersionResponse> MailId.MailIdWebservice.getVersionAsync(MailId.getVersionRequest request)
        {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailId.getVersionResponse> getVersionAsync()
        {
            MailId.getVersionRequest inValue = new MailId.getVersionRequest();
            inValue.Body = new MailId.getVersionRequestBody();
            return ((MailId.MailIdWebservice)(this)).getVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MailId))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MailId))
            {
                return new System.ServiceModel.EndpointAddress("https://api.campaign.episerver.net/soap11/MailId");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MailIdWebserviceClient.GetBindingForEndpoint(EndpointConfiguration.MailId);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MailIdWebserviceClient.GetEndpointAddress(EndpointConfiguration.MailId);
        }
        
        public enum EndpointConfiguration
        {
            
            MailId,
        }
    }
}
